algoritmo "ler matriz"
// Função :
// Autor :
// Data : 09/03/2023
// Seção de Declarações
var
mat:vetor[1..3,1..2] de inteiro
l,c:inteiro
inicio
para l <- 1 ate 3 faca
   Para c <- 1 ate  2 faca
         escreva("digite o valor da posição [",1,",",c,"]:" )
      leia(mat[l,c])

   fimpara
fimpara

Para l<-1 ate 3 faca
para c<-1 ate 2 faca
       escreva(mat[l,c])
fimpara
fimpara
Escreval()
fimalgoritmo
